// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8m7ofthsQxIyPP38QC-_YbOcsnjwAHQ',
    appId: '1:587706243824:web:21b5c3adef3997378d4035',
    messagingSenderId: '587706243824',
    projectId: 'flow-lens-3f987',
    authDomain: 'flow-lens-3f987.firebaseapp.com',
    storageBucket: 'flow-lens-3f987.firebasestorage.app',
    measurementId: 'G-5EV7NW91E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1o6KRj7xn_iQFgUvGkodDwbQ8DMng6U4',
    appId: '1:587706243824:android:6ba90d7fb6196b558d4035',
    messagingSenderId: '587706243824',
    projectId: 'flow-lens-3f987',
    storageBucket: 'flow-lens-3f987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1hU_E4IX2jasA6s1lGm7FZAgSxQR0Fs',
    appId: '1:587706243824:ios:02dec6662e95334d8d4035',
    messagingSenderId: '587706243824',
    projectId: 'flow-lens-3f987',
    storageBucket: 'flow-lens-3f987.firebasestorage.app',
    iosBundleId: 'com.example.flutterVideoAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1hU_E4IX2jasA6s1lGm7FZAgSxQR0Fs',
    appId: '1:587706243824:ios:02dec6662e95334d8d4035',
    messagingSenderId: '587706243824',
    projectId: 'flow-lens-3f987',
    storageBucket: 'flow-lens-3f987.firebasestorage.app',
    iosBundleId: 'com.example.flutterVideoAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj8m7ofthsQxIyPP38QC-_YbOcsnjwAHQ',
    appId: '1:587706243824:web:e67c9244a9f5d0a28d4035',
    messagingSenderId: '587706243824',
    projectId: 'flow-lens-3f987',
    authDomain: 'flow-lens-3f987.firebaseapp.com',
    storageBucket: 'flow-lens-3f987.firebasestorage.app',
    measurementId: 'G-VXX35P33QL',
  );
}
